name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLIC_URL: mpo.pulk.in
    steps:
    - uses: actions/checkout@v2

    - name: create CNAME
      run: |
        mkdir build
        echo "$PUBLIC_URL" > build/CNAME

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
