name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLIC_URL: mpo.pulk.in
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
    - run: |
    	npm i
    	npm ci
        npm run build
        echo "$PUBLIC_URL" > build/CNAME
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automatic Deploy action run by github-actions"
        git push origin HEAD:gh-pages --force

